###服务启动端口号
server:
  port: 8101
  servlet:
    context-path: /security
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
spring:
  application:
    name: api-security
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/security_test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000
  devtools:
    restart:
      enabled: true
  resources:
    static-locations: file:${web.upload-path}
  main:
    allow-bean-definition-overriding: true
  # 配置swagger访问账号密码
  #security:
  #  basic:
  #    enabled: true
  #    path: /swagger-ui.html
  #  user:
  #    name: admin
  #    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.security.mapper
  #配置sql打印日志,并且能打印数据库操作结果，但是会比较消耗性能,本地调试使用
  #configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # map-underscore-to-camel-case: true
#配置sql打印日志，无操作结果但是会返回行数，更省性能，服务器不打印返回结果
logging:
  level:
    com.ningdemgc.mapper: DEBUG #包路径为mapper文件包路径

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.security.mapper